# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property. You can also use the `cmake-args` property to
# pass flags to the build command and `artifact-name` to assign a name to
# distinguish build outputs from each other:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#   - board: nice_nano_v2
#     shield: corne_left
#     cmake-args: -DCONFIG_ZMK_USB_LOGGING=y
#     artifact-name: corne_left_with_logging
#
---
include:
  # ✅ 右手：普段用（snippet無し）
  - board: xiao_ble
    shield: roBa_R
    artifact-name: roBa_R_normal

  # ✅ 右手：Studio用（snippetあり）
  - board: xiao_ble
    shield: roBa_R
    snippet: studio-rpc-usb-uart
    artifact-name: roBa_R_studio

  # ✅ 左手：普段用
  - board: xiao_ble
    shield: roBa_L
    artifact-name: roBa_L

  # ✅ 設定全消し用
  - board: xiao_ble
    shield: settings_reset
    artifact-name: settings_reset
